# Generated by Django 5.2.17 on 2026-09-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="insurancebranch",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="insurancebranch",
            name="uniq_branch_per_company",
        ),
        migrations.RemoveIndex(
            model_name="insurancebranch",
            name="insurers_in_company_d46c41_idx",
        ),
        migrations.AddField(
            model_name="insurancebranch",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="branches", to="insurers.insurancecompany"
            ),
        ),
        migrations.AlterField(
            model_name="insurancebranch",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="branches_old",
                to="insurers.insurancecompany",
            ),
        ),
    ]
