# Generated by Django 5.2.17 on 2026-09-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0099_copy_branch_company_to_companies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancebranch",
            name="company",
        ),
    ]
