# Generated by Django 5.2.17 on 2026-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurers", "0100_remove_insurancebranch_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecompany",
            name="tat_hours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Follow-up TAT in hours for this client. Leave blank to use the global default.",
                null=True,
            ),
        ),
    ]
