# Generated by Django 5.2.17 on 2026-09-10 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("insurers", "0001_initial"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MIS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mis_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("mis_date", models.DateField()),
                (
                    "insurance_reference_number",
                    models.CharField(blank=True, max_length=60),
                ),
                ("lead_reference_id", models.CharField(blank=True, max_length=60)),
                (
                    "inspection_type",
                    models.CharField(default="Pre-Policy Inspection", max_length=60),
                ),
                ("intimator", models.CharField(blank=True, max_length=150)),
                ("remarks", models.TextField(blank=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("inspection_location", models.CharField(blank=True, max_length=255)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inspection_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "qc_stage",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("correction", "Correction Required"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=15,
                    ),
                ),
                (
                    "payment_stage",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("hold", "Hold"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mis_records",
                        to="insurers.insurancebranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mis_records",
                        to="customers.customer",
                    ),
                ),
                (
                    "field_executive",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "field_executive"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_mis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mis_records",
                        to="insurers.insurancecompany",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mis_records",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-mis_date", "-created_at"],
                "permissions": [
                    (
                        "assign_mis",
                        "Can assign or reassign a field executive to an MIS",
                    ),
                    ("export_mis_excel", "Can export MIS records to Excel"),
                    ("export_mis_pdf", "Can export MIS records to PDF"),
                    (
                        "view_financial_info",
                        "Can view financial/billing information on an MIS",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["mis_number"], name="mis_mis_mis_num_228608_idx"
                    ),
                    models.Index(
                        fields=["inspection_stage"], name="mis_mis_inspect_b7b366_idx"
                    ),
                    models.Index(
                        fields=["qc_stage"], name="mis_mis_qc_stag_b2b4c9_idx"
                    ),
                    models.Index(
                        fields=["insurance_company"], name="mis_mis_insuran_0cffb3_idx"
                    ),
                    models.Index(
                        fields=["field_executive"], name="mis_mis_field_e_3aa458_idx"
                    ),
                ],
            },
        ),
    ]
