# Generated by Django 5.2.17 on 2026-09-10 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mis", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mis",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mis_records",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="mis",
            index=models.Index(
                fields=["mis_number"], name="mis_mis_mis_num_228608_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mis",
            index=models.Index(
                fields=["inspection_stage"], name="mis_mis_inspect_b7b366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mis",
            index=models.Index(fields=["qc_stage"], name="mis_mis_qc_stag_b2b4c9_idx"),
        ),
        migrations.AddIndex(
            model_name="mis",
            index=models.Index(
                fields=["insurance_company"], name="mis_mis_insuran_0cffb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mis",
            index=models.Index(
                fields=["field_executive"], name="mis_mis_field_e_3aa458_idx"
            ),
        ),
    ]
