# Generated by Django 5.2.17 on 2026-09-10 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inspections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QCReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("not_recommended", "Not Recommended"),
                            ("need_correction", "Need Correction"),
                            ("reinspection_required", "Reinspection Required"),
                        ],
                        max_length=25,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qc_reviews",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "qc_executive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qc_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="qc.qcreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(
                        fields=["inspection", "-reviewed_at"],
                        name="qc_qcreview_inspect_beb7fb_idx",
                    )
                ],
            },
        ),
    ]
