# Generated by Django 5.2.17 on 2026-09-10 06:47

import apps.inspections.models
import apps.inspections.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        ("mis", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "odometer_reading",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("engine_condition", models.CharField(blank=True, max_length=100)),
                ("accessories_condition_notes", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_captured_at", models.DateTimeField(blank=True, null=True)),
                ("is_submitted", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "field_executive",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspection",
                        to="mis.mis",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "accept_inspection",
                        "Can accept an assigned inspection (field executive)",
                    ),
                    ("start_inspection", "Can mark an inspection as started"),
                    ("submit_inspection", "Can submit a completed inspection for QC"),
                    (
                        "assign_inspection",
                        "Can assign an inspection to a field executive",
                    ),
                    (
                        "reassign_inspection",
                        "Can reassign an inspection to a different field executive",
                    ),
                    ("upload_photo", "Can upload inspection photos"),
                    ("upload_video", "Can upload inspection videos"),
                    (
                        "download_media",
                        "Can download inspection photos/videos/documents",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event", models.CharField(max_length=150)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="inspections.inspection",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inspection status history",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PreviousInsurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_insurer", models.CharField(blank=True, max_length=150)),
                ("policy_number", models.CharField(blank=True, max_length=60)),
                ("policy_start_date", models.DateField(blank=True, null=True)),
                ("policy_end_date", models.DateField(blank=True, null=True)),
                ("had_previous_claim", models.BooleanField(default=False)),
                (
                    "claim_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "no_claim_bonus_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "policy_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.inspections.models.document_upload_path,
                        validators=[apps.inspections.validators.validate_document_file],
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_insurance",
                        to="inspections.inspection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InspectionAccessoryResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("present", models.BooleanField(default=True)),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.conditionoption",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessory_results",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.accessorymaster",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection", "item"),
                        name="uniq_accessory_per_inspection",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("rc", "RC (Registration Certificate)"),
                            ("insurance", "Insurance Policy Document"),
                            ("dl", "Driving License"),
                            ("owner_verification", "Registered Owner Verification"),
                            ("vehicle_number", "Vehicle Number Verification"),
                            ("engine_number", "Engine Number Verification"),
                            ("chassis_number", "Chassis Number Verification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.inspections.models.document_upload_path,
                        validators=[apps.inspections.validators.validate_document_file],
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection", "document_type"),
                        name="uniq_doctype_per_inspection",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionGlassResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.conditionoption",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glass_results",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.glassitemmaster",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection", "item"), name="uniq_glass_per_inspection"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionItemResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.conditionoption",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_results",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.inspectionitemmaster",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection", "item"), name="uniq_item_per_inspection"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.ImageField(
                        upload_to=apps.inspections.models.photo_upload_path,
                        validators=[apps.inspections.validators.validate_photo_file],
                    ),
                ),
                ("file_size", models.PositiveIntegerField(help_text="Bytes")),
                ("mime_type", models.CharField(max_length=50)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("capture_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="masters.photocategorymaster",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["inspection", "category"],
                        name="inspections_inspect_31209e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InspectionVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.inspections.models.video_upload_path,
                        validators=[apps.inspections.validators.validate_video_file],
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.inspections.models.video_thumb_path,
                    ),
                ),
                ("mime_type", models.CharField(max_length=50)),
                ("file_size", models.PositiveIntegerField(help_text="Bytes")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("capture_datetime", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence", models.PositiveSmallIntegerField(default=0)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=15,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="masters.videocategorymaster",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "replaces",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaced_by",
                        to="inspections.inspectionvideo",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["inspection", "category"],
                        name="inspections_inspect_43f5e9_idx",
                    ),
                    models.Index(
                        fields=["processing_status"],
                        name="inspections_process_e49419_idx",
                    ),
                ],
            },
        ),
    ]
