# Generated by Django 5.2.17 on 2026-09-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0001_initial"),
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="chassis_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="inspection",
            name="engine_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="inspection",
            name="verified_fuel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="masters.fueltype",
            ),
        ),
    ]
