# Generated by Django 5.2.17 on 2026-09-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inspections",
            "0002_inspection_chassis_number_inspection_engine_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="vehicle_colour",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="inspection",
            name="verified_manufacturing_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
