# Generated by Django 5.2.17 on 2026-09-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0003_inspection_vehicle_colour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="inspection_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
