# Generated by Django 5.2.17 on 2026-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_simplify_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="manufacturing_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
