# Generated by Django 5.2.17 on 2026-09-10 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("assign", "Assigned"),
                            ("upload", "Uploaded"),
                            ("download", "Downloaded"),
                            ("login", "Logged in"),
                            ("logout", "Logged out"),
                            ("export", "Exported"),
                            ("generate_report", "Generated report"),
                        ],
                        max_length=32,
                    ),
                ),
                ("module", models.CharField(max_length=64)),
                ("object_repr", models.CharField(max_length=255)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["module", "object_id"],
                        name="audit_audit_module_ebace4_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="audit_audit_user_id_e8be02_idx",
                    ),
                ],
            },
        ),
    ]
